name: 'OpenAPI Documention'
description: 'Generate HTML documentation from OpenAPI specification.'
inputs:
  title:
    description: 'Custom title for the HTML documentation'
    required: false
    default: 'API Documentation'
  file:
    description: 'File containing the API specification'
    required: false
    default: 'api.yaml'
  directory:
    description: 'Directory to output the HTML documentation'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.19'    
    
    - name: Run Go HTML Template Action
      run: go run ${{ github.action_path }}/main.go -title="${{ inputs.title }}" -file="${{ inputs.file }}" -directory="${{ inputs.directory }}"
      shell: bash
      env:
        github_repository: ${{ github.repository }}
